01 shell
maxkvant/SdHW pull request #1
Opened 2018-02-28 23:37 UTC by maxkvant

2018-03-26 10:57 UTC, yurii-litvinov requested changes
Нужно ещё текстовое описание деталей реализации, просто диаграммы недостаточно --- она только иллюстрация

2018-03-26 10:57 UTC, yurii-litvinov commented on 01-shell/src/main/scala/ru/spbau/maxim/Evaluator.scala
> +      case e: Exception => "parse error"
Мне кажется плохой идеей ловить все исключения вообще. Так поймаются исключения, указывающие на ошибки кодирования, а их ловить не стоит. Лучше ловить только те исключения, которые точно понятно откуда взялись

2018-03-26 10:57 UTC, yurii-litvinov commented on 01-shell/src/main/scala/ru/spbau/maxim/Evaluator.scala
> +  }
Очень неООПшно и довольно немасштабируемо. Если команд будет сотня и каждая из них будет иметь несколько десятков аргументов (как в настоящем bash), этот кусок кода превратится в ад.

2018-06-11 17:03 UTC, yurii-litvinov requested changes
По функциональности и архитектуре-то и так я был вполне доволен, а "архитектурное описание (диаграмма с классами и их взаимосвязями, немного текста, описывающего детали реализации)" так и не появилось. В частности, "немного текста, описывающего детали реализации", диаграмма-то ок. Не зачтена :)

2018-06-11 18:15 UTC, maxkvant commented
добавил описание

2018-06-12 14:32 UTC, yurii-litvinov approved these changes
Ну да, как-то так, зачтена.

2018-06-25 10:39 UTC, merged