added 11 grpc
maxkvant/SdHW pull request #2
Opened 2018-06-10 18:20 UTC by maxkvant

2018-06-11 17:14 UTC, yurii-litvinov requested changes

2018-06-11 17:14 UTC, yurii-litvinov commented on 11-grpc/gradlew
> +#!/usr/bin/env sh
Нет смысла выкладывать скрипты gradle wrapper-а, если не выкладывать сам gradle wrapper

2018-06-11 17:14 UTC, yurii-litvinov commented on 11-grpc/gradlew
> +#!/usr/bin/env sh
Ну и, кстати, gradle build не проходит с сообщением 
```
Execution failed for task ':generateProto'.
> Codegen plugin grpc not defined
```
Оно должно, если правильно настроено, укачивать и grpc правильной версии при сборке

2018-06-11 18:26 UTC, maxkvant commented on 11-grpc/gradlew
> +#!/usr/bin/env sh
idea подсвечивала жёлтым такие строчке в build.gradle:
plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:${grpcVersion}"
        }
 }
я их перед отправкой удалил, а оказалось, что они нужны

gradle-wrapper idea не добавила из-за gitignore

2018-06-12 14:52 UTC, yurii-litvinov approved these changes
Да, теперь всё работает. Зачтена.

2018-06-12 14:52 UTC, yurii-litvinov commented on 11-grpc/src/main/kotlin/ru/spbau/maxim/main.kt
> +        print(help)
Хех, поругались, но всё равно упали с ArrayIndexOutOfBoundsException

2018-06-12 14:57 UTC, maxkvant commented on 11-grpc/src/main/kotlin/ru/spbau/maxim/main.kt
> +        print(help)
поправил

2018-06-25 11:09 UTC, merged