hw2 grep
maxkvant/SdHW pull request #3
Opened 2018-06-12 22:31 UTC by maxkvant

2018-06-13 00:17 UTC, maxkvant commented
кажется, файлы в параметрах grep не просили указывать, поэтому предполагается такое использование:

`cat file | grep regex`

2018-06-14 07:57 UTC, yurii-litvinov requested changes
Ну, использовать cat для передачи файла в grep можно, но всё-таки хочется и синтаксис `grep regex file`, если это можно достаточно быстро сделать. В презентации в примерах всё-таки было именно так. Всё остальное норм. Если есть принципиальные проблемы с реализацией grep с файлом, готов зачесть и так :)

2018-06-14 11:00 UTC, maxkvant commented
добавил возможность передачи файла.

я обычному grep из bash передаю файлы через cat, поэтому счёл ненужным.

2018-06-15 06:04 UTC, yurii-litvinov approved these changes
```
grep -w -A scala build.sbt
[scallop] Error: Bad arguments for option 'A': 'scala' - bad Int value

Process finished with exit code 1
```
Мне кажется, раньше оно не заканчивало работу после ошибки. Впрочем, остальное всё ок, зачтена

2018-06-25 10:38 UTC, merged